# DB ?? ??
spring.datasource.url=jdbc:postgresql://40.82.146.221:5432/postgres?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=postgres1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Kafka Broker Address
spring.kafka.bootstrap-servers=40.82.146.221:9092


file.upload-path=C:/dev_storage/snack_shop