# DB ?? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Kafka Broker Address
#spring.kafka.bootstrap-servers=localhost:9092
spring.elasticsearch.uris= http://40.82.146.221:9200
file.upload-path=/snack_shop